### ISSUE TITLE
Aggregate posts from all locations

### ISSUE THREAD

**Issue by adam-binks** [stabubble/stabubbleweb#1]
Motivation: if there aren't many users from specific locations, they might be quiet

Possible solution: have an "all locations" view where bubbles from all locations are aggregated, with an "at badlands" indicator to show which location they're in. Similar to reddit /r/all!

**Comment by badlands** [comment]
Don't reference me please, I'm not a location :-)

**Comment by yryo617** [comment]
@adam-binks  let's escape that :p
